#ifndef CATLOVEDOG_RESOURCE_DATA_H
#define CATLOVEDOG_RESOURCE_DATA_H
#include "coolbar_GAME_Type.h"
#ifdef GAME_176_220
typedef enum
{
	CATLOVEDOG_BAOZHA_GIF,
	CATLOVEDOG_BEIJING_0_GIF,
	CATLOVEDOG_BEIJING_1_GIF,
	CATLOVEDOG_BEIJING_2_GIF,
	CATLOVEDOG_BORDER_GIF,
	CATLOVEDOG_BUTTON_GIF,
	CATLOVEDOG_CAT_GIF,
	CATLOVEDOG_DOG_GIF,
	CATLOVEDOG_GUTOU_GIF,
	CATLOVEDOG_LIFEC_GIF,
	CATLOVEDOG_LIFED_GIF,
	CATLOVEDOG_LILIANG_GIF,
	CATLOVEDOG_LOADING_GIF,
	CATLOVEDOG_LOADING1_GIF,
	CATLOVEDOG_LOGO_176_GIF,
	CATLOVEDOG_LOSE_GIF,
	CATLOVEDOG_MENU_GIF,
	CATLOVEDOG_SE_GIF,
	CATLOVEDOG_WIN_GIF,
	CATLOVEDOG_WIND_GIF,
	CATLOVEDOG_YUCI_GIF,
	CATLOVEDOG_BAD_MID,
	CATLOVEDOG_GOOD_MID,
	CATLOVEDOG_WIN_MID,
	CATLOVEDOG_END_OF_ID
}CATLOVEDOG_E;
#ifndef USE_MMC_RES_CATLOVEDOG
extern const unsigned char CatLoveDog_Resource_Data[];
extern tResource CatLoveDog_TResource_Data;
#else
extern tResource CatLoveDog_TResource_Data;
#endif
#endif
#ifdef GAME_240_320
typedef enum
{
	CATLOVEDOG_BAOZHA_GIF,
	CATLOVEDOG_BEIJING_0_GIF,
	CATLOVEDOG_BEIJING_1_GIF,
	CATLOVEDOG_BEIJING_2_GIF,
	CATLOVEDOG_BORDER_GIF,
	CATLOVEDOG_BUTTON_GIF,
	CATLOVEDOG_CAT_GIF,
	CATLOVEDOG_DOG_GIF,
	CATLOVEDOG_GUTOU_GIF,
	CATLOVEDOG_LIFEC_GIF,
	CATLOVEDOG_LIFED_GIF,
	CATLOVEDOG_LILIANG_GIF,
	CATLOVEDOG_LOADING_GIF,
	CATLOVEDOG_LOADING1_GIF,
	CATLOVEDOG_LOGO_176_GIF,
	CATLOVEDOG_LOSE_GIF,
	CATLOVEDOG_MENU_GIF,
	CATLOVEDOG_SE_GIF,
	CATLOVEDOG_WIN_GIF,
	CATLOVEDOG_WIND_GIF,
	CATLOVEDOG_YUCI_GIF,
	CATLOVEDOG_BAD_MID,
	CATLOVEDOG_GOOD_MID,
	CATLOVEDOG_WIN_MID,
	CATLOVEDOG_END_OF_ID
}CATLOVEDOG_E;
#ifndef USE_MMC_RES_CATLOVEDOG
extern const unsigned char CatLoveDog_Resource_Data[];
extern tResource CatLoveDog_TResource_Data;
#else
extern tResource CatLoveDog_TResource_Data;
#endif
#endif
#endif
