#ifndef RUSSBLOCK_RESOURCE_DATA_H
#define RUSSBLOCK_RESOURCE_DATA_H
#include "coolbar_GAME_Type.h"
#ifdef GAME_176_220
typedef enum
{
	RUSSBLOCK_B0_GIF,
	RUSSBLOCK_B1_GIF,
	RUSSBLOCK_B2_GIF,
	RUSSBLOCK_B3_GIF,
	RUSSBLOCK_B4_GIF,
	RUSSBLOCK_B5_GIF,
	RUSSBLOCK_B6_GIF,
	RUSSBLOCK_BG_GIF,
	RUSSBLOCK_BIAOQINGT_GIF,
	RUSSBLOCK_BOTTOM_GIF,
	RUSSBLOCK_BZ1_GIF,
	RUSSBLOCK_BZ3_GIF,
	RUSSBLOCK_CLEAR_GIF,
	RUSSBLOCK_CMD_GIF,
	RUSSBLOCK_CURSORS_GIF,
	RUSSBLOCK_ENTERGAME_GIF,
	RUSSBLOCK_GAMEOVER_GIF,
	RUSSBLOCK_HELP_GIF,
	RUSSBLOCK_HITEFFECT_GIF,
	RUSSBLOCK_INGAMEMENU_GIF,
	RUSSBLOCK_LEFTFRAME_GIF,
	RUSSBLOCK_LOADING_GIF,
	RUSSBLOCK_LOADING1_GIF,
	RUSSBLOCK_LOGOITEM1_GIF,
	RUSSBLOCK_LOGOITEM2_GIF,
	RUSSBLOCK_MENUBAR_GIF,
	RUSSBLOCK_MENUWORD_GIF,
	RUSSBLOCK_MNTY_GIF,
	RUSSBLOCK_PANEL_GIF,
	RUSSBLOCK_PROPBAR_GIF,
	RUSSBLOCK_PROPCHOOSE_GIF,
	RUSSBLOCK_PROPKEY_GIF,
	RUSSBLOCK_PROPNUM_GIF,
	RUSSBLOCK_RENWU_GIF,
	RUSSBLOCK_RTX_GIF,
	RUSSBLOCK_SCORE_NUM_GIF,
	RUSSBLOCK_SICENGLXG_GIF,
	RUSSBLOCK_TIME_GIF,
	RUSSBLOCK_TOP_GIF,
	RUSSBLOCK_WENZI6_GIF,
	RUSSBLOCK_WENZI7_GIF,
	RUSSBLOCK_WENZI8_GIF,
	RUSSBLOCK_XCXIAOGUO_GIF,
	RUSSBLOCK_XIAJIANG_GIF,
	RUSSBLOCK_BZXG_ACTOR,
	RUSSBLOCK_ERASE_ACTOR,
	RUSSBLOCK_FALLFAST_ACTOR,
	RUSSBLOCK_GIRLFIRST_ACTOR,
	RUSSBLOCK_GIRLTWO_ACTOR,
	RUSSBLOCK_HX_ACTOR,
	RUSSBLOCK_RWBQ_ACTOR,
};
#ifndef USE_MMC_RES_RUSSBLOCK
extern const char RussBlock_Resource_Data[];
extern tResource RussBlock_TResource_Data;
#else
extern tResource RussBlock_TResource_Data;
#endif
#endif
#ifdef GAME_240_320
typedef enum
{
	RUSSBLOCK_B0_GIF,
	RUSSBLOCK_B1_GIF,
	RUSSBLOCK_B2_GIF,
	RUSSBLOCK_B3_GIF,
	RUSSBLOCK_B4_GIF,
	RUSSBLOCK_B5_GIF,
	RUSSBLOCK_B6_GIF,
	RUSSBLOCK_BG_GIF,
	RUSSBLOCK_BOTTOM_GIF,
	RUSSBLOCK_BZ1_GIF,
	RUSSBLOCK_BZ3_GIF,
	RUSSBLOCK_CLEAR_GIF,
	RUSSBLOCK_CMD_GIF,
	RUSSBLOCK_CURSORS_GIF,
	RUSSBLOCK_ENTERGAME_GIF,
	RUSSBLOCK_GAMEOVER_GIF,
	RUSSBLOCK_GIRLFACE_GIF,
	RUSSBLOCK_HELP_GIF,
	RUSSBLOCK_HITEFFECT_GIF,
	RUSSBLOCK_INGAMEMENU_GIF,
	RUSSBLOCK_KULS_GIF,
	RUSSBLOCK_LEFTFRAME_GIF,
	RUSSBLOCK_LOADING_GIF,
	RUSSBLOCK_LOADING1_GIF,
	RUSSBLOCK_LOGOITEM1_GIF,
	RUSSBLOCK_LOGOITEM2_GIF,
	RUSSBLOCK_MENUBAR_GIF,
	RUSSBLOCK_MENUWORD_GIF,
	RUSSBLOCK_MNTY_GIF,
	RUSSBLOCK_PANEL_GIF,
	RUSSBLOCK_PROPBAR_GIF,
	RUSSBLOCK_PROPCHOOSE_GIF,
	RUSSBLOCK_PROPKEY_GIF,
	RUSSBLOCK_PROPNUM_GIF,
	RUSSBLOCK_RTX_GIF,
	RUSSBLOCK_RWBQ_GIF,
	RUSSBLOCK_SCORE_NUM_GIF,
	RUSSBLOCK_SICENGLXG_GIF,
	RUSSBLOCK_TIME_GIF,
	RUSSBLOCK_TOP_GIF,
	RUSSBLOCK_WENZI6_GIF,
	RUSSBLOCK_WENZI7_GIF,
	RUSSBLOCK_WENZI8_GIF,
	RUSSBLOCK_WENZI9_GIF,
	RUSSBLOCK_XCXG_GIF,
	RUSSBLOCK_XIAJIANG_GIF,
	RUSSBLOCK_BZXG_ACTOR,
	RUSSBLOCK_ERASE_ACTOR,
	RUSSBLOCK_FALLFAST_ACTOR,
	RUSSBLOCK_GIRLFIRST_ACTOR,
	RUSSBLOCK_GIRLTWO_ACTOR,
	RUSSBLOCK_HX_ACTOR,
	RUSSBLOCK_RWBQ_ACTOR,
};
#ifndef USE_MMC_RES_RUSSBLOCK
extern const char RussBlock_Resource_Data[];
extern tResource RussBlock_TResource_Data;
#else
extern tResource RussBlock_TResource_Data;
#endif
#endif
#endif
