#ifndef ONFF_RESOURCE_DATA_H
#define ONFF_RESOURCE_DATA_H
#include "coolbar_GAME_Type.h"
#ifdef GAME_176_220
typedef enum
{
	ONFF_BACKGROUND_GIF,
	ONFF_BORDER_GIF,
	ONFF_BOSS1_GIF,
	ONFF_BOSS2_GIF,
	ONFF_BOSS3_GIF,
	ONFF_BOSS4_GIF,
	ONFF_BULLET_GIF,
	ONFF_ENEMY_GIF,
	ONFF_ENEMY_BOMB_GIF,
	ONFF_FONT_GIF,
	ONFF_GUANGBIAO_GIF,
	ONFF_ICON_GIF,
	ONFF_LOADING_GIF,
	ONFF_LOADING1_GIF,
	ONFF_LOGO_176_GIF,
	ONFF_MENU_BAR_GIF,
	ONFF_MENU_MAP_GIF,
	ONFF_MENU_MAP_0_GIF,
	ONFF_MENU_POINT_GIF,
	ONFF_MENU_TITLE_GIF,
	ONFF_PLAYER_EFFECT_GIF,
	ONFF_PLAYER_K_GIF,
	ONFF_PLAYER_MAIN_GIF,
	ONFF_PLAYER_SHOW_GIF,
	ONFF_PRIZE_GIF,
	ONFF_TEST1_GIF,
	ONFF_END_OF_ID
}ONFF_E;
#ifndef USE_MMC_RES_ONFF
extern const unsigned char ONFF_Resource_Data[];
extern tResource ONFF_TResource_Data;
#else
extern tResource ONFF_TResource_Data;
#endif
#endif
#ifdef GAME_240_320
typedef enum
{
	ONFF_BACKGROUND_GIF,
	ONFF_BORDER_GIF,
	ONFF_BOSS1_GIF,
	ONFF_BOSS2_GIF,
	ONFF_BOSS3_GIF,
	ONFF_BOSS4_GIF,
	ONFF_BULLET_GIF,
	ONFF_ENEMY_GIF,
	ONFF_ENEMY_BOMB_GIF,
	ONFF_FONT_GIF,
	ONFF_GUANGBIAO_GIF,
	ONFF_ICON_GIF,
	ONFF_LOADING_GIF,
	ONFF_LOADING1_GIF,
	ONFF_LOGO_176_GIF,
	ONFF_MENU_BAR_GIF,
	ONFF_MENU_MAP_GIF,
	ONFF_MENU_MAP_0_GIF,
	ONFF_MENU_POINT_GIF,
	ONFF_MENU_TITLE_GIF,
	ONFF_PLAYER_EFFECT_GIF,
	ONFF_PLAYER_K_GIF,
	ONFF_PLAYER_MAIN_GIF,
	ONFF_PLAYER_SHOW_GIF,
	ONFF_PRIZE_GIF,
	ONFF_TEST1_GIF,
	ONFF_END_OF_ID
}ONFF_E;
#ifndef USE_MMC_RES_ONFF
extern const unsigned char ONFF_Resource_Data[];
extern tResource ONFF_TResource_Data;
#else
extern tResource ONFF_TResource_Data;
#endif
#endif
#endif
