#ifndef HITMOLE_RESOURCE_DATA_H
#define HITMOLE_RESOURCE_DATA_H
#include "coolbar_GAME_Type.h"
#ifdef GAME_176_220
typedef enum
{
	HITMOLE_BEIJING0_GIF,
	HITMOLE_BEIJING1_GIF,
	HITMOLE_BEIJING2_GIF,
	HITMOLE_BEIJING3_GIF,
	HITMOLE_BIAOTI_GIF,
	HITMOLE_BORDER_GIF,
	HITMOLE_CHUIZI1_GIF,
	HITMOLE_CHUIZI2_GIF,
	HITMOLE_CHUIZI3_GIF,
	HITMOLE_DISHU1_GIF,
	HITMOLE_DISHU2_GIF,
	HITMOLE_DISHU3_GIF,
	HITMOLE_ICON_GIF,
	HITMOLE_LABA_GIF,
	HITMOLE_LOADING_GIF,
	HITMOLE_LOADING1_GIF,
	HITMOLE_LOGO_176_GIF,
	HITMOLE_SHU1_MID,
	HITMOLE_SHU2_MID,
	HITMOLE_WIN_MID,
	HITMOLE_END_OF_ID
}HITMOLE_E;
#ifndef USE_MMC_RES_HITMOLE
extern const unsigned char HitMole_Resource_Data[];
extern tResource HitMole_TResource_Data;
#else
extern tResource HitMole_TResource_Data;
#endif
#endif
#ifdef GAME_240_320
typedef enum
{
	HITMOLE_BEIJING0_GIF,
	HITMOLE_BEIJING1_GIF,
	HITMOLE_BEIJING2_GIF,
	HITMOLE_BEIJING3_GIF,
	HITMOLE_BIAOTI_GIF,
	HITMOLE_BORDER_GIF,
	HITMOLE_CHUIZI1_GIF,
	HITMOLE_CHUIZI2_GIF,
	HITMOLE_CHUIZI3_GIF,
	HITMOLE_DISHU1_GIF,
	HITMOLE_DISHU2_GIF,
	HITMOLE_DISHU3_GIF,
	HITMOLE_ICON_GIF,
	HITMOLE_LABA_GIF,
	HITMOLE_LOADING_GIF,
	HITMOLE_LOADING1_GIF,
	HITMOLE_LOGO_176_GIF,
	HITMOLE_SHU1_MID,
	HITMOLE_SHU2_MID,
	HITMOLE_WIN_MID,
	HITMOLE_END_OF_ID
}HITMOLE_E;
#ifndef USE_MMC_RES_HITMOLE
extern const unsigned char HitMole_Resource_Data[];
extern tResource HitMole_TResource_Data;
#else
extern tResource HitMole_TResource_Data;
#endif
#endif
#endif
